accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/signin.html', extra_context={'login_page': "active"}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('account-info/', views.account_info, name='account-info'),
    path('account-member', views.confirm_member, name='confirm-member'),
    path('account-spots/', views.account_spots, name='account-spots'),
    path('account-payments/', views.account_payments, name='account-payments'),
]

parkingapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')), # could change to accounts page
    path('payments/', include('payments.urls')),
    path('parkview/', include('parkview.urls')),
    path('admin/', admin.site.urls),
]

parkview/urls.py
from django.urls import path
from . import views

app_name = 'parkview'
urlpatterns = [
    path('', views.GaragesView.as_view(), name='garages'),
    path('<int:garage_id>/', views.spots, name='spots'),
    path('<int:spot_id>/spot', views.parkspot, name='parkspot'),
    path('license/', views.add_license, name='license')
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'
urlpatterns = [
    path('payment/', views.payment_page, name='payment-page'),
    path('payment-complete/', views.payment_complete, name='payment-complete'),
]

testnewuser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy
from django.utils import timezone
from datetime import timedelta

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)

        customer = Customer()
        customer.save()
        user.customer = customer

        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Customer(models.Model): # for tracking payments
    cid = models.AutoField(primary_key=True)

    def __str__(self):
        return f'customer {self.cid}'


class User(AbstractUser): # an account
    """User model."""
    username = None
    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    email    = models.EmailField(ugettext_lazy('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return f'user {self.email}'


def after30days():
    return timezone.now() + timedelta(days=30)
    
class Member(models.Model):
    user       = models.OneToOneField(User, on_delete=models.CASCADE)    
    start_date = models.DateField(auto_now_add=True)
    end_date   = models.DateField(default=after30days)

    def __str__(self):
        return f'member of {self.user}'

payments/models.py
from django.db import models
from accounts.models import Customer
from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField
# Create your models here.

class CreditCard(models.Model):
    customer  = models.OneToOneField(Customer, on_delete=models.CASCADE)
    cc_name   = models.CharField(max_length=50)
    cc_number = CardNumberField('card number')
    cc_expiry = CardExpiryField('expiration date')
    cc_code = SecurityCodeField('security code')

    def __str__(self):
        return f'Card: {self.cc_number}'


class Payment(models.Model):
    paid_by = models.ForeignKey(CreditCard, on_delete=models.PROTECT, related_name='payments')
    date    = models.TimeField(auto_now_add=True)
    amount  = models.IntegerField()

    def __str__(self):
        name = getattr(self.paid_by, 'cc_name')
        return f'{self.amount} paid by {name} on {self.date}'

accounts/forms.py
from django import forms
from accounts.models import User
from payments.models import CreditCard
from django.contrib.auth.forms import UserCreationForm

class UserSignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']

payments/forms.py
from django import forms
from creditcards.forms import CardNumberField, CardExpiryField, SecurityCodeField
from .models import CreditCard


class AddCreditCard(forms.ModelForm):
    cc_name = forms.CharField(label='Name on Card')
    cc_number = CardNumberField(label='Card Number')
    cc_expiry = CardExpiryField(label='Expiration Date')
    cc_code = SecurityCodeField(label='CVV/CVC')

    class Meta:
        model = CreditCard
        fields = ['cc_name', 'cc_number', 'cc_expiry', 'cc_code']

accounts/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from payments.models import CreditCard, Payment
from payments.forms import AddCreditCard
from parkview.forms import AddLicenseForm
from parkview.models import License
from parkview.views import get_confirm_response

from .models import Customer, Member
from .forms import UserSignupForm, UserUpdateForm

def home(request):
    return render(request, 'accounts/home.html', {'title': 'Home'})

def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            customer = Customer()
            customer.save()
            user.customer = customer
            user.save()
            messages.success(request, f'Your account has been created!')
            login(request, user)
            return redirect('/account-info')
    else:
        form = UserSignupForm()
    return render(request, 'accounts/signin.html', {'create_page': "active", 'form': form})

@login_required
def confirm_member(request):
    if hasattr(request.user, 'member'):
        return redirect('/account-info')

    elif request.method == 'POST':
        response = get_confirm_response(request)
        if response == 'confirm':
            try:
                credit_card = CreditCard.objects.get(customer=request.user.customer)
            except CreditCard.DoesNotExist:
                messages.warning(request, 'You must add a credit card')
                return redirect('/account-payments')
            
            member = Member(user=request.user)
            payment = Payment(paid_by=credit_card, amount=10) # 10 bucks
            member.save()
            payment.save()
            messages.success(request, 'Your membership was successfully created!')
        # cancel and success
        return redirect('/account-info')

    return render(request, 'accounts/member.html', {'user': request.user})

@login_required
def account_info(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        l_form = AddLicenseForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('/account-info')
        elif l_form.is_valid():
            plate = License(value=l_form.cleaned_data['value'], owner=request.user.customer)
            try:
                plate.save()
            except IntegrityError:
                messages.error(request, 'License already exists')
                return redirect('/account-info')

            messages.success(request, f'Your license plate has been updated!')
            return redirect('/account-info')
    else:
        u_form = UserUpdateForm(instance=request.user)
        l_form = AddLicenseForm(instance=request.user)

    context = {
        'u_form': u_form,
        'l_form': l_form,
        'plates': request.user.customer.licenses.all()
    }

    return render(request, 'accounts/account.html', context)


def account_spots(request):
    return render(request, 'accounts/spots.html', {'title':'Spots'})

@login_required
def account_payments(request):
    customer = request.user.customer
    try:
        credit_card = CreditCard.objects.get(customer=customer)
        have_card =True
    except CreditCard.DoesNotExist:
        have_card = False

    if request.method == 'POST':
        add_form = AddCreditCard(request.POST, instance=request.user)
        if add_form.is_valid():
            if not have_card: credit_card = CreditCard(customer=customer)
            
            credit_card.cc_name = add_form.cleaned_data['cc_name']
            credit_card.cc_number = add_form.cleaned_data['cc_number']
            credit_card.cc_expiry = add_form.cleaned_data['cc_expiry']
            credit_card.cc_code = add_form.cleaned_data['cc_code']
            credit_card.save()

            messages.success(request, f'Your card has been {"updated" if have_card else "added"}!')
            return redirect('/account-payments')
    else:
        add_form = AddCreditCard(instance=request.user)

    context = {'title': 'Payments', 'form': add_form}
    if have_card:
        context = {**context, **{'card': credit_card}}


    return render(request, 'accounts/payments.html', context)

payments/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import IntegrityError
from parkview.models import ParkingSpot, License
from accounts.models import Customer
from .models import CreditCard, Payment
from .forms import AddCreditCard
from datetime import timedelta, date

# Create your views here

def payment_page(request):
    if request.method == 'POST':
        add_form = AddCreditCard(request.POST)
        if add_form.is_valid():
            if str(request.user) != 'AnonymousUser':
                customer = request.user.customer
            else:
                customer = Customer.objects.get(cid=request.session['cid'])
            try:
                credit_card = CreditCard.objects.get(customer=customer)
            except CreditCard.DoesNotExist:
                credit_card = CreditCard(customer=customer)

            credit_card.cc_name = add_form.cleaned_data['cc_name']
            credit_card.cc_number = add_form.cleaned_data['cc_number']
            credit_card.cc_expiry = add_form.cleaned_data['cc_expiry']
            credit_card.cc_code = add_form.cleaned_data['cc_code']
            credit_card.save()
            
        else:
            try:
                credit_card = CreditCard.objects.get(customer=request.user.customer)
            except AttributeError: # bad form
                messages.error(request, f'Invalid values entered in the credit card')
                return redirect('/payments/payment')
 
        payment = Payment(paid_by=credit_card, amount=10)
        spot = ParkingSpot.objects.get(id=request.session['spot'])
        spot.used_by = License.objects.get(id=request.session['plate'])

        try:
            payment.save()
            spot.save()
        except IntegrityError:
            messages.error(request, 'License is already used')
            return redirect('/parkview/license/')

        messages.success(request, f'Your payment was successful')
        request.session['billing_name'] = credit_card.cc_name
        request.session['cc_number'] = credit_card.cc_number
        request.session['amount'] = payment.amount
        return redirect('/payments/payment-complete')

    # blank form
    add_form = AddCreditCard()
    context = {'title': 'Payments', 'form': add_form}

    if str(request.user) != 'AnonymousUser':
        try:
            credit_card = CreditCard.objects.get(customer=request.user.customer)
            context = {**context, **{'card': credit_card}}
        except CreditCard.DoesNotExist: #do not add to context
            pass

    return render(request, 'payments/payment.html', context)


def payment_complete(request):

    context = {
        'title': 'Payment Complete',
        'billing_name': request.session['billing_name'],
        'amount': request.session['amount'],
        'cc_number': request.session['cc_number'],
        'spot': ParkingSpot.objects.get(id=request.session['spot']),
        'plate': License.objects.get(id=request.session['plate']),
        'exp_date': date.today() + timedelta(days=30)
    }

    return render(request, 'payments/payment-complete.html', context)

accounts/templates/accounts/account.html
{% extends "accounts/base-account.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container jumbo">
  <div class="content-section">
      <div class="media">
          <div class="media-body">
            <h2 class="account-heading">Hi, {{ user.first_name }}</h2>
          </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Account Info</legend>
              {{ u_form | crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
  </div>
</div>
<div class="container jumbo">
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <h3 class="account-heading">License Plates</h3>
                {% if plates|length > 0 %}
                    <ul class="list-group">
                        {% for plate in plates %}
                            <li class="list-group-item">Plate: {{ plate.value }}</li>
                        {% endfor %}
                    </li>
                {% else %}
                    <p>You have no license plates</p>
                {% endif %}
            </div>
        </div>
        <div class="move">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Add Plate</legend>
                    {{ l_form | crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/base-account.html
{% extends "accounts/base.html" %}

{% block sidebar %}
<div class="container jumbo">
  <div class="content-section">
    <div class="media">
      <div class="media-body">
          <h2 class="account-heading">Links</h2>
      </div>
    </div>
    <ul class="list-group">
        <li class="list-group-item list-group-item-action option-btn">
          <a href="{% url 'accounts:account-info' %}" class="stretched-link text-decoration-none">
            Information</a>
        </li>
        <li class="list-group-item list-group-item-action option-btn">
          <a href="{% url 'accounts:account-payments' %}" class="stretched-link text-decoration-none">
            Payment</a>
        </li>
        <li class="list-group-item list-group-item-action option-btn">
          <a href="{% url 'accounts:account-spots' %}" class="stretched-link text-decoration-none">
            Spots</a>
        </li>
        {% if user.member %}
          <li class="list-group-item option-btn disabled">
            <a href='#'>
              Member since {{ user.member.start_date }}</a>
          </li>
        {% else %}
          <li class="list-group-item list-group-item-action option-btn">
            <a href="{% url 'accounts:confirm-member' %}" class="stretched-link text-decoration-none">
              Member Sign Up</a>
          </li>
        {% endif %}
    </ul>
  </div>
</div>
{% endblock sidebar %}

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="https://static.thenounproject.com/png/72-200.png">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'accounts/main.css' %}">

    {% if title %}
    <title>CS 487 Final Project - {{ title }}</title>
    {% else %}
    <title>CS 487 Final Project</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'accounts:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'parkview:garages' %}">Garages</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'accounts:account-info' %}">Account</a>
                        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link {{ login_page }}" href="{% url 'accounts:login' %}">Login</a>
                        <a class="nav-item nav-link {{ create_page }}" href="{% url 'accounts:signup' %}">Sign Up</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-lg-9 col-md-15">
                {% if messages %}
                    {% for message in messages%}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-lg-3 col-md-15">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </main>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/home.html
{% extends "accounts/base.html" %}
{% block content %}
<div class="container jumbo">
  <div class="content-section">
    <h1 class="display display-style">Parking App</h1>
    <p class="lead">You may use our services as a guest, or sign up for a membership.</p>
    <hr class="questions">
    <p>If you have any questions, contact us at: (000)-000-0000</p>
    <p class="lead">
    </p>
  </div>
<div>
{% endblock content %}

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html xml:lang="en" lang="en">

<!--
    this page will be a login screen to login to an account
    should also have tabs to create an account, or login as guest
-->

<head>

</head>

<body>

</body>

accounts/templates/accounts/logout.html
{% extends "accounts/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'accounts:login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

accounts/templates/accounts/member.html
{% extends "parkview/confirm.html" %}
{% include "accounts/base-account.html" %}

{% block prompt %}

<h1>Become a Member {{ user.first_name }}!</h1>
<p>
    Are you sure you want to become a member?
    (A member will charge you a monthly amount 
    on your credit card)
</p>
{% endblock %}\

accounts/templates/accounts/payments.html
{% extends "accounts/base-account.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container jumbo">
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h2 class="account-heading">{{ user.first_name }}'s Payment Methods</h2>
        </div>
    </div>
</div>

<div class="content-section">
    <div class="media">
        <div class="media-body">
        <legend class="border-bottom mb-4">{{ user.first_name }}'s Credit Card</legend>
        {% if card %}
            <p>Card ending in **** {{ card.cc_number.12 }}{{ card.cc_number.13 }}{{ card.cc_number.14 }}{{ card.cc_number.15 }}</p>
            <p>Expires {{ card.cc_expiry }}</p>
        {% else %}
            <p>No cards added.</p>
        {% endif %}
        </div>
    </div>
    
    <div class="move">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {% if card %}
                    <legend class="border-bottom mb-4">Update Card</legend>
                {% else %}
                    <legend class="border-bottom mb-4">Add Card</legend>
                {% endif %}
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                {% if card %}
                    <button class="btn btn-outline-info" type="submit">Update</button>
                {% else %}
                    <button class="btn btn-outline-info" type="submit">Add</button>
                {% endif %}
            </div>
        </form>
    </div>
</div>

</div>
{% endblock content %}

accounts/templates/accounts/signin.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container jumbo">
  <div class="content-section">
      <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">
                  {% if create_page %} Join Today
                  {% else %}           Log In
                  {% endif %}
              </legend>
              {{ form | crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">
                  {% if create_page %} Sign Up
                  {% else %}           Log In
                  {% endif %}
              </button>
          </div>
      </form>
      <div class="border-top pt-3">
          <small class="text-muted">
              {% if create_page %}
              Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
              {% else %}
              Need An Account? <a class="ml-2" href="{% url 'accounts:signup' %}">Sign Up Now</a>
              {% endif %}
          </small>
      </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/spots.html
{% extends "accounts/base-account.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container jumbo">
<div class="content-section">
    <div class="media">
        <div class="media-body">
            <h2 class="account-heading">{{ user.first_name }}'s Current Spots</h2>
        </div>
    </div>
    <div>
        <p>
            Need to get another spot? <a class="ml-2" href="#">View Available Spots</a>
        </p>
    </div>
</div>
</div>
{% endblock content %}