accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/signin.html', extra_context={'login_page': "active"}), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('account-info/', views.account_info, name='account-info'),
    path('account-member', views.confirm_member, name='confirm-member'),
    path('account-spots/', views.account_spots, name='account-spots'),
    path('account-payments/', views.account_payments, name='account-payments'),
]

parkingapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')), # could change to accounts page
    path('payments/', include('payments.urls')),
    path('parkview/', include('parkview.urls')),
    path('admin/', admin.site.urls),
]

parkview/urls.py
from django.urls import path
from . import views

app_name = 'parkview'
urlpatterns = [
    path('', views.GaragesView.as_view(), name='garages'),
    path('<int:garage_id>/', views.spots, name='spots'),
    path('<int:spot_id>/spot', views.parkspot, name='parkspot'),
    path('license/', views.add_license, name='license')
]

testnewuser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

parkview/models.py
from django.db import models
from accounts.models import Customer

# Create your models here.

class License(models.Model):
    value = models.CharField(max_length=7, unique=True)
    owner = models.ForeignKey(Customer, on_delete=models.PROTECT, related_name='licenses')
    
    def __str__(self):
        return f'License {self.value} for {self.owner}'


class TempLicense(models.Model):
    plate  = models.OneToOneField(License, on_delete=models.CASCADE, related_name='temporary')
    expire = models.DateField()

    def __str__(self):
        return str(self.plate)


class ParkingGarage(models.Model):
    name     = models.CharField(max_length=30)
    street   = models.CharField(max_length=100)
    city     = models.CharField(max_length=100)
    country  = models.CharField(max_length=25)
    zip_code = models.IntegerField()
    floors   = models.IntegerField()
    price    = models.IntegerField()

    def __str__(self):
        return f'{self.name} on {self.street} in {self.city}, {self.country}'


class ParkingSpot(models.Model):
    floor   = models.IntegerField(default=1)
    used_by = models.OneToOneField(License, on_delete=models.PROTECT, blank=True, null=True)
    garage  = models.ForeignKey(ParkingGarage, on_delete=models.PROTECT, related_name='spots')

    def user(self):
        return 'no one' if self.used_by is None \
          else self.used_by

    def __str__(self):
        return f'{self.garage.name} on floor {self.floor} used by {self.user()}'

parkview/forms.py
from django import forms
from .models import License


class AddLicenseForm(forms.ModelForm):
    value = forms.CharField(max_length=7, label='Plate Number')

    class Meta:
        model = License
        fields = ['value']

parkview/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.contrib import messages
from django.utils.datastructures import MultiValueDictKeyError

from accounts.models import Customer
from .models import ParkingGarage, ParkingSpot, License
from .forms import AddLicenseForm

# Create your views here.

def spots(request, garage_id):
    garage = get_object_or_404(ParkingGarage, pk=garage_id)
    floors = [garage.spots.filter(floor=num) for num in range(1,garage.floors+1)]
    context = {'garage': garage, 'floors': floors}
    return render(request, 'parkview/spots.html', context)

def get_confirm_response(request):
    try:
        response = request.POST['confirm'].lower()
    except MultiValueDictKeyError:
        response = 'cancel'
    return response

def parkspot(request, spot_id):
    spot = get_object_or_404(ParkingSpot, pk=spot_id)
    if request.method == 'POST':
        response = get_confirm_response(request)
        if response == 'confirm':
            request.session['spot'] = spot_id
            return redirect(f'/parkview/license')
        else:
            return redirect(f'/parkview/{spot.garage.id}')
            
    return render(request, 'parkview/spot-confirm.html', {'spot': spot})


def add_license(request):
    if request.method == 'POST':
        add_form = AddLicenseForm(request.POST)
        if add_form.is_valid():
            if str(request.user) != 'AnonymousUser':
                owner = request.user.customer
            else:
                customer = Customer()
                customer.save()
                owner = customer
            plate = License(value=add_form.cleaned_data['value'], owner=owner)
            plate.save()

        elif 'choice' in request.POST:
            license_id = request.POST['choice']
            plate = License.objects.get(id=license_id)
        else:
            messages.error(request, 'License is invalid')
            return redirect('/parkview/license')
        
        request.session['plate'] = plate.id
        if str(request.user) == 'AnonymousUser':
            request.session['cid'] = plate.owner.cid

        return redirect('/payments/payment')

    add_form = AddLicenseForm()
    context = {
        'title': 'Payments',
        'form': add_form
    }
    if str(request.user) != 'AnonymousUser':
        licenses = request.user.customer.licenses.all()
        context = {**context, **{'licenses': licenses}}

    return render(request, 'parkview/add-license.html', context)


class GaragesView(generic.ListView):
    template_name = 'parkview/garages.html'
    context_object_name = 'nearby_garages'

    def get_queryset(self):
        """get the 10 closest garages"""
        # no loc calc right now
        return getattr(ParkingGarage, 'objects').all()[:10]

parkview/templates/parkview/add-license.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container jumbo">
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <h2 class="account-heading">License Plate</h2>
            </div>
        </div>
        
        {% if licenses and licenses|length >= 1 %}
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <div class="move">
                <legend class="border-bottom mb-4">Use An Existing Plate</legend>
                {% for license in licenses %}
                    <div class="radiobtn">
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ license.id }}">
                    <label for="choice{{ forloop.counter }}">{{ license.value }}</label>
                {% endfor %}
                </div>
            </fieldset>
            <div class="form-group">
                <input class="btn btn-outline-info" type="submit" value="Use License">
            </div>
        </form>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <div class="move">
                <legend class="border-bottom mb-4">Add License Plate</legend>
                {{ form | crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Add</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

parkview/templates/parkview/confirm.html
{% extends "accounts/base.html" %}

{% block content %}
    
<div class="container jumbo">
    <div class="content-section">
        {% block prompt %}
        {% endblock prompt %}

        <form method="POST">
        {% csrf_token %}
            <input type="submit" class="btn btn-outline-info" name="confirm" id="choice1" value="Confirm">
            <input type="submit" class="btn btn-outline-info" name="confirm" id="choice2" value="Cancel">
        </form>
    </div>
</div>
{% endblock content %}

parkview/templates/parkview/garages.html
{% extends "accounts/base.html" %}
{% block content %}

<div class="container jumbo">
<h1>Parking Garages Near Me</h1>
<hr class="break brk">
</div>

{% if nearby_garages %}
    <ul class="list-group">
    {% for garage in nearby_garages %}
        <li class="list-group-item list-group-item-action garages-text option-btn">
            <a class="stretched-link text-decoration-none" href="{% url 'parkview:spots' garage.id %}">{{ garage.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No garages are nearby</p>
{% endif %}

{% endblock content %}

parkview/templates/parkview/spot-confirm.html
{% extends "parkview/confirm.html" %}
{% block prompt %}
<h1>Confirm Selection</h1>
<p>
    Do you want to select this spot in {{ spot.garage.name }}
    on Floor {{ spot.floor }}?
</p>
{% endblock prompt %}

parkview/templates/parkview/spots.html
{% extends "accounts/base.html" %}
{% block content %}

<div class="container jumbo">
<div class="cntr">
    <h1>{{ garage.name }}</h1>

    <ul class="list-inline">
        <p class="garage_text gtext">{{ garage.street }}
        {{ garage.city }}, {{ garage.country }}
        {{ garage.zip_code }}</p>
    </ul>
    </div>
</div>

<h2 class="move">Parking Spots</h2>
{% for floor in floors %}
    <h3 class="move">Floor {{ forloop.counter }}</h3>
    <div class="list-group d-flex flex-row flex-wrap">
    {% for spot in floor %}
        {% if spot.used_by is None %}
            <a class="col-md-4 list-group-item list-group-item-action option-btn"
                href="{% url 'parkview:parkspot' spot.id %}">Open</a>
        {% else %}
            <a class="col-md-4 list-group-item disabled" href="#">Used by {{ spot.used_by.value }}</a>
        {% endif %}
    {% endfor %}
    </div>
{% endfor %}

{% endblock content %}